#
# Specific services to work with KNP Menu
#

parameters:
    
    fbfb.twig_extension.class: FlorianBelhomme\Bundle\FoundationBundle\Twig\MenuExtension

services:
    
    fbfb.twig_extension:
        class: %fbfb.twig_extension.class%
        arguments:
            - @knp_menu.helper
            - %florian_belhomme_foundation.template.breadcrumb%
        tags:
            - { name: twig.extension }
